"""
Django settings for store project.

Generated by 'django-admin startproject' using Django 5.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""
import os
import cloudinary
import cloudinary.uploader
import cloudinary.api
from pathlib import Path

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-841je$-_sk7@0lri@v3dl9@2un07l3*kuzqcf7#144cuqgktir'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['a1techlib.shop','a1techstore.onrender.com','.now.sh', '127.0.0.1', 'localhost']


# Application definition

INSTALLED_APPS = [
    'jazzmin',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'cloudinary',
    'cloudinary_storage',
    'django.contrib.staticfiles',
    'accounts',
    'products',
]


# Cloudinary configuration
cloudinary.config(
    cloud_name='dfueppsdg',
    api_key='616474895267773',
    api_secret='JN2GsI5yw6_rGf8-dzMW-2MjWoo'
)

CLOUDINARY_STORAGE = {
    'CLOUD_NAME': 'dfueppsdg',
    'API_KEY': '616474895267773',
    'API_SECRET': 'JN2GsI5yw6_rGf8-dzMW-2MjWoo',
}




MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]


JAZZMIN_SETTINGS = {
    "site_title": "A1-Tech",
    "site_header": "Admin Dashboard",
    "welcome_sign": "Welcome to A1-Tech Store",
    "show_ui_builder": False,  # Set to True to enable UI Builder
    "show_apps": True,
    "icons": {"auth": "fas fa-users", "accounts": "fas fa-wallet", "products": "fas fa-cube"},
    "related_modal_active": False,
    "changeform_format": "horizontal_tabs",  # "horizontal_tabs" or "vertical_tabs"
    "changeform_format_overrides": {
        "auth.user": "vertical_tabs",
    },
    "collapsible_sidebar": True,
    "navigation_expanded": True,
    "hide_apps": [],  # List of app labels to hide
    "hide_models": [],  # List of model names to hide
    "related_modal_active": True,  # Enable related modal in change form
    "custom_css": None,  # URL to custom CSS file
    "custom_js": None,  # URL to custom JavaScript file
    "show_language_switcher": False,  # Set to True to enable language switcher
    "languages": [  # List of languages for the switcher
        {"code": "en", "name": "English"},
        {"code": "es", "name": "Spanish"},
    ],
}


ROOT_URLCONF = 'store.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]


WSGI_APPLICATION = 'store.wsgi.application'


# Database
# https:/#/docs.djangoproject.com/en/5.0/ref/settings/#databases

#DATABASES = {
#    'default': {
#        'ENGINE': 'django.db.backends.sqlite3',
#        'NAME': BASE_DIR / 'db.sqlite3',
#    }
#}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': 'railway',
        'USER': 'postgres',
        'PASSWORD': 'uUxizBQqjBALdfEHbDjKAviEXrQjnrMS',
        'HOST': 'roundhouse.proxy.rlwy.net',
        'PORT': '31362',
    }
}


# Email Configuration for Gmail SMTP
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_USE_SSL = False
EMAIL_HOST_USER = 'joannabedella@gmail.com'  # Your Gmail address
EMAIL_HOST_PASSWORD = 'ncfesqwtekvpeghr'  # Your Gmail password or App Password


# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/

STATIC_URL = 'static/'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
]

MEDIA_URL = "/images/"
MEDIA_ROOT = BASE_DIR

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
