# Generated by Django 5.0.2 on 2024-03-16 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='description',
            field=models.TextField(default='no description'),
        ),
        migrations.AddField(
            model_name='product',
            name='embed_link',
            field=models.URLField(default='https://www.a1lib.com'),
        ),
    ]
