# Generated by Django 5.0.2 on 2024-04-11 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_description_product_embed_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='elvis',
            name='promo_code',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
